import os
from crewai import Agent, Task, Crew, Process

# Mocking LLM setup for the sake of the project compilation
os.environ["OPENAI_API_KEY"] = "mock_key_for_demo_purposes"

class ResearchCrew:
    def __init__(self, topic):
        self.topic = topic

    def setup_agents(self):
        researcher = Agent(
            role='Senior Research Analyst',
            goal=f'Uncover cutting-edge developments in {self.topic}',
            backstory="You work at a leading tech think tank.",
            verbose=True,
            allow_delegation=False
        )
        
        writer = Agent(
            role='Tech Content Strategist',
            goal=f'Craft a compelling article on {self.topic}',
            backstory="You are a renowned Tech Blogger known for insightful articles.",
            verbose=True,
            allow_delegation=True
        )
        
        return researcher, writer

    def setup_tasks(self, researcher, writer):
        task1 = Task(
            description=f'Conduct a comprehensive analysis of the latest advancements in {self.topic}.',
            expected_output='A full analysis report in bullet points.',
            agent=researcher
        )
        
        task2 = Task(
            description=f'Using the insights provided, write an engaging blog post about {self.topic}.',
            expected_output='A 4 paragraph blog post formatted in markdown.',
            agent=writer
        )
        
        return [task1, task2]

    def run(self):
        researcher, writer = self.setup_agents()
        tasks = self.setup_tasks(researcher, writer)
        
        crew = Crew(
            agents=[researcher, writer],
            tasks=tasks,
            process=Process.sequential
        )
        
        # In a real environment, crew.kickoff() would be called.
        # result = crew.kickoff()
        return "Simulated execution: The article has been generated by the agents."

if __name__ == "__main__":
    crew_pipeline = ResearchCrew("Quantum Computing in 2026")
    print(crew_pipeline.run())
